services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${ENV}_${APP_NAME}_redis
    restart: unless-stopped
    command: >
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY:-400mb}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - mynet
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-512M}

networks:
  mynet:
    driver: bridge
    name: ${ENV}_${APP_NAME}_network
