upstream {{ENV}}_{{APP_NAME}} {
    server 127.0.0.1:{{REDIS_PORT}};
}

server {
    listen {{REDIS_PORT}};
    proxy_pass {{ENV}}_{{APP_NAME}};

    proxy_connect_timeout 10s;
    proxy_timeout 300s;
}